backend = "glx";

# Максимально сильные тени
shadow = true;

# Увеличиваем ширину свечения до 16 пикселей
shadow-radius = 14;

# Сдвигаем координаты строго в минус для равномерности по всему периметру
shadow-offset-x = -14;
shadow-offset-y = -14;
animation = true
# Абсолютная плотность (максимальная сила без прозрачности)
shadow-opacity = 1.0;

# Выставляем чистый, максимально яркий красный цвет (1.0 — это предел)
shadow-red = 1.0;
shadow-green = 0.0;
shadow-blue = 0.1;

# Исключения для панелей (чтобы не затенять бар vxwm)
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'vxwm'"
];

# Сохраняем острые углы и фикс для vxwm
corner-radius = 0;
frame-opacity = 1.0;

# Жесткая оптимизация для слабого ПК
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
vsync = false;
blur-background = false;
fading = false;
unredir-if-possible = true;
